main:
  game_config:
    tictactoe:
      c: 1
      n_simulation: 500
      simulation_time: 5
    connect4:
      c: 1
      n_simulation: 1000
      simulation_time: 99999
    knucklebones:
      c: 1
      n_simulation: 5000
      simulation_time: 99999
  log_config:
    level: 20 # DEBUG: 10, INFO: 20, ERROR = 40
    format: "%(asctime)s [%(levelname)s] : %(message)s"

EVE:
  nproc: 8
  game_id: 0
  n_round: 50
  game_config:
    tictactoe:
      c:
        - 1
      simulation_time:
        - 100000
      n_simulation:
        - 25
        - 50
        - 100
        - 200
        # - 500
        # - 1000
    connect4:
      c:
        - 1
      simulation_time:
        - 100000
      n_simulation:
        - 100
        - 250
        - 500
        - 1000
        - 2000
    knucklebones:
      c: 
        - 1
      simulation_time:
        - 100000
      n_simulation:
        # - 8
        # - 40
        - 200
        # - 1000
        # - 5000
    knucklebones_open:
      c: 
        - 1
      simulation_time:
        - 100000
      n_simulation:
        # - 8
        # - 40
        - 200
        # - 1000
        # - 5000
  log_config:
    filemode: w
    level: 20 # DEBUG: 10, INFO: 20, ERROR = 40
    format: "%(asctime)s [%(levelname)s] : %(message)s"